#!/bin/bash

sudo tc qdisc add dev eth0 root netem delay 70ms
docker exec mapo125
#docker run -ti --rm -p 1230:1230 dayaftmapo:latest
#ping google.com
sudo tc qdisc del dev eth0 root netem delay 70ms
